AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-todo

  Sample SAM Template for sam-todo
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  TaskFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: task/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Policies: AmazonDynamoDBFullAccess
      Environment:
                Variables:
                    PARAM1: VALUE
      Events:
        TaskList:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /task
            Method: get
        CreateTask:
          Type: Api
          Properties:
            Path: /task
            Method: put

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SamTodoApi:
    Description: "API Gateway endpoint URL for Prod stage for SamTodo function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/todo/"
  SamTodoFunction:
    Description: "SamTodo Lambda Function ARN"
    Value: !GetAtt SamTodoFunction.Arn
  SamTodoFunctionIamRole:
    Description: "Implicit IAM Role created for SamTodo function"
    Value: !GetAtt SamTodoFunctionRole.Arn
